//This file was generated by script swreg2regmap.py

//register address mapping
#define DATA_1 0
#define DATA_2 1
#define DATA_OUT 2
#define DONE 3
#define SOLVER_SEL 4
#define SEL 5
#define KNN_RESET 6
