//This file was generated by script swreg2regmap.py

//register address mapping
#define DATA_IN 0
#define DATA0_OUT 1
#define DATA1_OUT 2
#define DATA2_OUT 3
#define DATA3_OUT 4
#define KNN_RESET 5
#define DONE 6
