//START_TABLE sw_reg
`SWREG_W(DATA_IN, DATA_W, 0)//Data input register
`SWREG_R(DATA0_OUT, DATA_W/4, 0)
`SWREG_R(DATA1_OUT, DATA_W/4, 0)
`SWREG_R(DATA2_OUT, DATA_W/4, 0)
`SWREG_R(DATA3_OUT, DATA_W/4, 0)
`SWREG_W(KNN_RESET, 1, 0)
`SWREG_W(DONE, 1, 0)
